runmode: debug
addr: 9001
name: coral
url: http://localhost:9001
max_ping_count: 10
jwt_secret: qazxswedcvfrtgbnhyujmkiol0987654321
tls:
  addr: 9002
  cert: conf/server.crt
  key: conf/server.key
log:
  writers: stdout
  logger_level: DEBUG
  logger_file: log/coral.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: coral
  addr: 127.0.0.1:3306
  username: root
  password: golang